### ISSUE TITLE
TUN DNS拦截失败

### ISSUE THREAD

**Issue by longls777** [nelvko/clash-for-linux-install#108]
日志：
```
(base) lsl@dual3090:/data/lsl/.git$ clash update
😾 没有提供有效的订阅链接：使用 /opt/clash/config.yaml 进行更新...
👌 备份配置：/opt/clash/config.yaml.bak
[sudo] password for lsl: 
🍃 订阅更新成功
(base) lsl@dual3090:/data/lsl/.git$ clash tun on
😼 Tun 状态：启用
(base) lsl@dual3090:/data/lsl/.git$ dig api.binance.com

; <<>> DiG 9.18.30-0ubuntu0.20.04.2-Ubuntu <<>> api.binance.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61972
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;api.binance.com.               IN      A

;; Query time: 7 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Apr 14 02:05:48 CST 2025
;; MSG SIZE  rcvd: 44
```
/opt/clash/mixin.yaml配置：
```
# Web 控制台配置
external-controller: '127.0.0.1:9090'
external-ui: public
secret:
# tun 配置
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true # clash
  auto-redirect: true # mihomo
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  strict-route: true
  exclude-interface:
  # - docker0
  # - podman0 
# DNS 配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
```
/etc/systemd/resolved.conf配置:
```
[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
DNSOverTLS=no
#Cache=no-negative
#DNSStubListener=yes
#ReadEtcHosts=yes
```
cat /etc/resolv.conf配置：
```
nameserver 127.0.0.53
options edns0 single-request-reopen
```
按理来说TUN会拦截53端口的DNS请求，然后转发到0.0.0.0:1053？但是开启TUN后，dig显示仍然是走的; SERVER: 127.0.0.53#53(127.0.0.53) (UDP) 这个DNS路由，而没有走1053，导致DNS解析失败；在我将systemd的DNSStubListener设置为no 且/opt/clash/mixin.yaml配置的DNS listen: 0.0.0.0:1053改成53端口后，DNS可以正常解析，但是关闭clash后，由于没有了默认的127.0.0.53:53，导致DNS全部解析失败。 请问为什么TUN没有拦截成功发送给127.0.0.53:53的DNS请求？
